# Generated by Django 5.1.6 on 2025-03-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
