# Generated by Django 5.1.6 on 2025-03-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
