# Generated by Django 5.1.6 on 2025-03-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0004_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerbid',
            name='cover_letter',
        ),
    ]
