# Generated by Django 5.1.6 on 2025-03-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0006_client_remove_freelancerbid_freelnacer1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='company_phone',
        ),
    ]
