# Generated by Django 5.1.6 on 2025-03-22 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0007_rename_phone_client_company_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeLancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addhar_image', models.ImageField(upload_to='freelancer_aadhar')),
                ('linkedin_url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_freelancer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
