# Generated by Django 5.1.6 on 2025-03-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0009_freelancer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='category',
        ),
    ]
