# Generated by Django 5.1.6 on 2025-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0010_remove_freelancer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
