# Generated by Django 5.1.5 on 2025-03-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0012_freelancer_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Freelancer_profile',
        ),
    ]
