# Generated by Django 5.1.5 on 2025-04-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0014_project_daily_updates_alter_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_daily_updates',
            name='hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
