# Generated by Django 5.1.5 on 2025-04-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0015_alter_project_daily_updates_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_daily_updates',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
