# Generated by Django 5.1.5 on 2025-04-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0016_alter_project_daily_updates_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_daily_updates',
            old_name='Task_Details',
            new_name='task_Details',
        ),
    ]
