# Generated by Django 5.1.5 on 2025-04-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0017_rename_task_details_project_daily_updates_task_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_daily_updates',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='project_daily_updates',
            name='task_Details',
        ),
        migrations.AddField(
            model_name='project_daily_updates',
            name='task_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
