# Generated by Django 5.1.5 on 2025-04-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0018_remove_project_daily_updates_project_name_and_more'),
        ('freelanceruser_app1', '0019_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_daily_updates',
            name='freelancer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='freelancer_app3.freelancer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_daily_updates',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_updates', to='freelanceruser_app1.projectnew'),
            preserve_default=False,
        ),
    ]
