# Generated by Django 5.1.5 on 2025-04-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0019_project_daily_updates_freelancer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_daily_updates',
            name='assigned_freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freelancer_app3.freelancer'),
        ),
    ]
