# Generated by Django 5.1.5 on 2025-04-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0022_project_daily_updates_assigned_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_daily_updates',
            name='assigned_freelancer',
        ),
    ]
