# Generated by Django 5.1.5 on 2025-04-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0024_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='msg',
        ),
    ]
