# Generated by Django 5.1.5 on 2025-04-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceradmin_app2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adminuser',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserManagement',
        ),
    ]
