# Generated by Django 5.1.6 on 2025-03-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='project_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
