# Generated by Django 5.1.6 on 2025-03-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0002_alter_user_company_name_alter_user_company_website_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
