# Generated by Django 5.1.6 on 2025-03-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
