# Generated by Django 5.1.6 on 2025-03-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelanceruser_app1', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='client_profiles/')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_projects_posted', models.IntegerField(default=0)),
                ('completed_projects', models.IntegerField(default=0)),
                ('hiring_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('reviews_count', models.IntegerField(default=0)),
                ('preferred_payment_method', models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer')], max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
