# Generated by Django 5.1.6 on 2025-03-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='reviews_count',
        ),
        migrations.AddField(
            model_name='client',
            name='feedback',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
