# Generated by Django 5.1.6 on 2025-03-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0007_remove_client_reviews_count_client_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='client_profiles'),
            preserve_default=False,
        ),
    ]
