# Generated by Django 5.1.6 on 2025-03-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0010_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
