# Generated by Django 5.1.6 on 2025-03-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0013_projectnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnew',
            name='project_image',
            field=models.ImageField(default=1, upload_to='project_imag'),
            preserve_default=False,
        ),
    ]
