# Generated by Django 5.1.6 on 2025-03-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0014_projectnew_project_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientPayment',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
