# Generated by Django 5.1.6 on 2025-03-25 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0015_delete_client_delete_clientpayment_delete_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnew',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectnew',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProjectResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('budget', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(blank=True, default='Pending', max_length=255, null=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_freelancer', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_response', to='freelanceruser_app1.projectnew')),
            ],
        ),
    ]
