# Generated by Django 5.1.6 on 2025-03-25 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0016_projectnew_is_assigned_projectnew_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnew',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_freelancer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectresponse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
