# Generated by Django 5.1.6 on 2025-03-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0017_projectnew_freelancer_projectresponse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnew',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectnew',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
