# Generated by Django 5.1.6 on 2025-03-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0018_projectnew_is_paid_projectnew_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
