# Generated by Django 5.1.5 on 2025-04-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0019_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresponse',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
