# Generated by Django 5.1.5 on 2025-04-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0020_projectresponse_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectresponse',
            name='is_approved',
        ),
    ]
