# Generated by Django 5.1.5 on 2025-04-08 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app3', '0021_remove_project_daily_updates_assigned_freelancer'),
        ('freelanceruser_app1', '0021_remove_projectresponse_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnew',
            name='assigned_freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freelancer_app3.freelancer'),
        ),
    ]
