# Generated by Django 5.1.5 on 2025-04-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceruser_app1', '0024_projectnew_assigned_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectnew',
            name='assigned_freelancer',
        ),
    ]
